### ISSUE TITLE
Does cbuf require Elixir 1.6 

### ISSUE THREAD

**Issue by arnomi** [ckampfe/cbuf#2]
Hi @ckampfe,

is there a particular reason that Cbuf specifies in its mix.exs that it requires at least Elixir 1.6. As far as I can tell it runs fine on Elixr 1.5.2.

Thanks in advance

**Comment by ckampfe** [comment]
Hey @arnomi I don't believe it requires 1.6, that's probably just what I had active while developing. I'll give it a spin with 1.5 and try to confirm

**Comment by ckampfe** [comment]
fixed in 0271abeda418e0a52898c20e229628b03b1fca16 . Thank you @arnomi
